---

- block:

  - name: Adding vhosts configuration
    template:
      src: 127.0.0.1.vhost.conf.j2
      dest: "/etc/nginx/conf.d/{{ item.url }}.conf"
      mode: 0644
      owner: root
      group: root
    with_items: "{{ vhosts }}"
    notify:
      - Reload Nginx

  when: enabled_vhosts
